### ISSUE TITLE
Could not find riot game path

### ISSUE THREAD

**Issue by null15** [lithellx/RiotLogin#1]
![image](https://github.com/lithellx/RiotLogin/assets/30800470/42d6f2ca-1177-427b-9d9b-5cbf324f94ab)

Any idea how to fix? Tried these paths:

D:\Games\Riot Games\Riot Client
D:\Games\Riot Games\Riot Client\UX
D:\Games\Riot Games\Riot Client\RiotClientElectron
D:\Games\Riot Games\League of Legends
D:\Games\Riot Games\League of Legends\Game

To no avail

**Comment by lithellx** [comment]
Select Riot Games path not Riot Client.

![image](https://github.com/lithellx/RiotLogin/assets/45209073/6d07c6ca-1d22-448e-975b-75afa2348597)

D:\Games\Riot Games
